- functions.sh
Each comment is divided into four parts:
* Description of the function
* Global variables used and modified
* Arguments taken
* Returned values other than the default exit status of the last command run
The idea was borrowed from Shell Style Guide by Google.
> Comment each function in functions.sh

- README.md
- bootstrap/11-pm.sh
- bootstrap/14-networking.sh
- functions.sh
- pieman.sh
> Add DNS-related parameters

- pieman.sh
> Do not show root password

- pieman.sh
> Make docker-pieman.sh more portable

- README.md
- bootstrap/14-networking.sh
- files/etc/hostname.template
- files/etc/hosts.template
- pieman.sh
> Add HOST_NAME parameter

- README.md
- devices/rpi-2-b/ubuntu-artful-armhf/README.md
- devices/rpi-2-b/ubuntu-artful-armhf/cmdline.txt
- devices/rpi-2-b/ubuntu-artful-armhf/config.txt
- devices/rpi-2-b/ubuntu-artful-armhf/fix-kernel-installation-in-chroot.patch
- devices/rpi-2-b/ubuntu-artful-armhf/pieman.yml
- devices/rpi-2-b/ubuntu-artful-armhf/pre-kernel-installation/10-patch-flash-kernel.sh
- devices/rpi-2-b/ubuntu-artful-armhf/pre-second-stage/10-remove-bash-from-required.sh
- devices/rpi-2-b/ubuntu-artful-armhf/pre-upgrade/10-remove-unpacked-bash.sh
- devices/rpi-3-b/ubuntu-artful-armhf
32bit for Raspberry Pi 2 and 3.
> Add Ubuntu "Artful" 17.10

- .travis.yml
- pieman.sh
* Adapt `pieman.sh` to `shellcheck`
* Make Travis CI run `shellcheck` to lint only `pieman.sh` so far
> shellcheck

- functions.sh
- pieman.sh
Now, when we figure out the size of the target image after assembling the chroot environment, we win a few and we lose a few. Pieman became a bit flexible since it doesn't create an image with the size of 7 GB for all occasions, but the target image may turn out not large enough for the rootfs. The previous approach to calculating of the target image size figured out (via `du`) how much space we need to store the rootfs and created the partition with the size. However, the approach didn’t take into account the file system metadata size, so in some cases there was no enough space to store the rootfs. The current logic fixes it.
> Use more sophisticated approach to calculating image size

- bootstrap/10-rootfs-partition.sh
- bootstrap/11-pm.sh
- pieman.sh
* Mark keys as trusted only when creating chroot
* Create kering only when creating chroot
> Do not call some functions twice when it's not necessary

- README.md
- bootstrap/11-pm.sh
- functions.sh
- pieman.sh
- test/test_functions.sh
The params are:
* `ENABLE_BZIP2`
* `ENABLE_GZIP`
* `ENABLE_XZ`
> Add compress params

- .travis.yml
See details at https://github.com/travis-ci/travis-ci/issues/9484.
> Fix Travis issue related to shellcheck

- devices/rpi-2-b/devuan-jessie-armhf/pieman.yml
* add `udev` to `includes`;
* remove `tzdata` from `base`.
> Devuan enhancments

- README.md
- docker/Dockerfile
- essentials.sh
- test/test_functions.sh
Otherwise Ubuntu 18.04 LTS (Bionic Beaver) fails
> Use debootstrap 1.0.105

- helpers/fs.sh
> Don't remove project directory if CREATE_ONLY_CHROOT=true

- devices/rpi-2-b/ubuntu-bionic-armhf/fix-kernel-installation-in-chroot.patch
- devices/rpi-2-b/ubuntu-bionic-armhf/pre-kernel-installation/10-patch-flash-kernel.sh
- devices/rpi-3-b/ubuntu-bionic-arm64/fix-kernel-installation-in-chroot.patch
- devices/rpi-3-b/ubuntu-bionic-arm64/pre-kernel-installation/10-patch-flash-kernel.sh
> Fix kernel installation in Ubuntu 18.04 based chroot

- README.md
- pieman.sh
> Set COMPRESS_WITH_GZIP to false by default

- pieman/bin/du.py
Resolves #100 
Added `-m` or `--size-in-megabytes` option.
It returns total size rounded up
> Add -m option to du.py

- README.md
> Expand the list of the dependencies in README with pandoc

- pieman.sh
> Check toolset only after all other checks are done

- toolset.sh
> Improve message output when toolset is ready

- README.md
- pieman.sh
> Add IMAGE_ROOTFS_SIZE parameter to set up the size of rootfs in megabytes

- helpers/base.sh
> Do not give volume name boot to any FAT partition

- pieman.sh
See mendersoftware/mender-convert@b1a3ac8ed344e531e2aa2a51b9cc907fac153cc3
> Set correct attributes for 'device_type' file

- README.md
- files/mender/mender.conf.template
- helpers/mender.sh
- pieman.sh
> Add mender params

- bootstrap/12-pm.sh
> Install ca-certificates to Mender artifact

- files/mender/mender.conf.template
> Remove quotes for numeric elements in mender.conf

- .travis.yml
- helpers/apk.sh
- pieman/bin/apk_tools_version.py
- pieman/bin/du.py
- pieman/bin/image_attrs.py
- pieman/pieman/__init__.py
- pieman/pieman/attrs.py
- pieman/setup.py
Checklist for testing:
* Remove pieman from virtualenv or anything else place (depends on where you have installed it).
* Install pieman usnig `python3 setup.py install`.
* Build an image based on Alpine Linux.
* Build one more image based on, for example, Ubuntu Bionic 64bit.
> Set up Travis CI for pylint

- README.md
> README: add Running images in emulator section

- AUTHORS.md
- helpers/toolset.sh
- toolset.sh
> Figure out how many processor cores are available and use the number when building U-Boot

- pieman/requirements.txt
> Specify PyYAML version in requirements.txt

- devices/opi-pc-plus/debian-buster-armhf/pieman.yml
> Use wildcards in opi-pc-plus/debian-buster-armhf/pieman.yml

- devices/rpi-3-b/ubuntu-bionic-arm64/pieman.yml
> Use bcm2710-rpi-3-b.dtb for Ubuntu Bionic 64-bit on RPi 3

- README.md
> README: add macOS High Sierra to Supported platforms

- README.md
> README: add missing opi-zero short name

- devices/opi-zero/debian-buster-armhf/README.md
> Fix Orange Pi model in README for opi-zero/debian-buster-armhf

- devices/opi-pc-plus/debian-buster-armhf/README.md
- devices/opi-pc-plus/kali-rolling-armhf/README.md
> Fix links of Orange Pi model in README for opi-ps-plus

- README.md
- docker/Dockerfile
- helpers/base.sh
> Do not mention PyYAML in README and do not check the dependency

- README.md
- helpers/apk.sh
- helpers/deb.sh
- helpers/mender.sh
- pieman.sh
- test/test_functions.sh
- toolset.sh
> Track  toolset version

- README.md
> README: move supported devices and OSes above

- doc/components.md
> Describe Pieman components

- AUTHORS.md
- README.md
- bootstrap/12-pm.sh
- bootstrap/40-deskop.sh
- files/desktop/06xfce4.desktop
- helpers/pm.sh
- pieman.sh
> Desktop environment work

- AUTHORS.md
- helpers/toolset.sh
> Make the package variable in get_qemu_emulation_binary function local 

- .gitignore
- README.md
- pieman.sh
> Add possibility to specify params in .env file

- bootstrap/40-deskop.sh
- files/desktop/lxdm.conf
> Default desktop environment

- bootstrap/12-pm.sh
> Add a channel that provides security updates in Debian and Ubuntu

- README.md
> Describe missing dependencies in README

- AUTHORS.md
- README.md
> Fix typo in README.md

- .travis.yml
- helpers/base.sh
- helpers/deb.sh
- helpers/mender.sh
- helpers/others.sh
- helpers/uboot.sh
- pieman.sh
- test/mocks.sh
- test/test_functions.sh
> Install shellcheck from Debian repository when Travis CI runs

- bootstrap/40-deskop.sh
> Fix bug with condition in bootstrap/40-deskop.sh

- docker/Dockerfile
> docker: copy qemu-arm-static and qemu-aarch64-static to /usr/bin

- essentials.sh
- toolset.sh
> Fix typo in Mender

- .travis.yml
> Allow unauthenticated in Travis CI

- helpers/uboot.sh
Related to 29fb8a5c42a463fefc1f0a331249cefeeb018446.
> Specify Python 2 explicitly in helpers/uboot.sh

- README.md
> Recommend installing e2fsprogs when using Fedora

- docker/Dockerfile
> docker: bump alpine version to 3.10

- docker/Dockerfile
> docker: install pieman package from branch but not from PyPI

- AUTHORS.md
- pieman.sh
> Recommend using balenaEtcher instead of Etcher

- AUTHORS.md
- helpers/base.sh
> Invert blocks Globals and Arguments in the split_os_name_into_pieces description 

- README.md
- devices/rpi-b/raspbian-buster-armhf/README.md
- devices/rpi-b/raspbian-buster-armhf/pieman.yml
- devices/rpi-zero-w/raspbian-buster-armhf
- pieman.sh
Raspbian Buster will be the first operating system for it.
> Add Raspberry Pi Zero W support

- essentials.sh
- pieman.sh
- test/test_essentials.sh
> Add def_private_var

- .travis.yml
- bootstrap/10-rootfs-partition.sh
- bootstrap/11-locale.sh
- bootstrap/12-pm.sh
- bootstrap/13-kernel.sh
- bootstrap/14-boot-partition.sh
- bootstrap/15-networking.sh
- bootstrap/20-users.sh
- bootstrap/30-fixes.sh
- bootstrap/50-firstboot.sh
- essentials.sh
- helpers/apk.sh
- helpers/base.sh
- helpers/bsc.sh
- helpers/fs.sh
- helpers/image-attribs.sh
- helpers/misc.sh
- helpers/network.sh
- helpers/templates.sh
The changes were tested using `sudo env PYTHONPATH="$(pwd)"/pieman PYTHON="$(pwd)"/../pieman-env/bin/python ENABLE_WIRELESS=true OS=raspbian-buster-armhf DEVICE=rpi-zero-w INCLUDES=mc,htop ./pieman.sh`.
`.env` was storing `WPA_SSID=CusDebAP`.
The following things were tested successfully:
* running tests (both written in Python and Bash);
* installing the specified packages;
* wireless networking;
* using the specified locale;
* creating a user with the specified username and password.
---
> Make bootstrap/*.sh meet shellcheck requirements

- helpers/base.sh
> Make is_debian_based leverage is_debian, is_devuan, is_kali, is_raspbian and is_ubuntu

- README.md
- devices/rpi-4-b/raspbian-buster-armhf
- devices/rpi-b/raspbian-buster-armhf/README.md
- devices/rpi-b/raspbian-buster-armhf/pieman.yml
Raspbian Buster will be the first operating system for it.
> Add Raspberry Pi 4

- helpers/image-attribs.sh
> Check exit code directly in get_attr function

- test/test_functions.sh
> Add test for get_attr function

- pieman/README.md
- pieman/setup.py
> Add missing utils descriptions to pieman/README.md

- pieman/pieman/__init__.py
903ec7d7317ee7b0cae94f972e2f57a32dc0dc3a should have done it.
---
> Correct pieman package version in pieman/pieman/__init__.py

- helpers/base.sh
> Check exit codes directly in check_dependencies function

- helpers/base.sh
See also https://github.com/tolstoyevsky/pieman/pull/248.
---
> Check exit code directly in check_pieman_version function

- helpers/base.sh
* It's used throughout the toolset.
* README references to it as a mandatory dependency.
---
> Make xz mandatory dependency

- README.md
- devices/rpi-2-b/alpine-3.12-armhf/README.md
- devices/rpi-2-b/alpine-3.12-armhf/pieman.yml
- devices/rpi-3-b-plus/alpine-3.12-armhf
Basic support of Alpine 3.12: only wired networking.
---
> Introduce Raspberry Pi 3 Model B+ (rpi-3-b-plus)

- depend_on.sh
- mutually_exclusive_params.sh
- pieman.sh
Closes https://github.com/tolstoyevsky/pieman/issues/240.
---
> Move calling check_mutually_exclusive_params and depend_on to separate scripts

- pieman.sh
It seems redundant -- if the file doesn't exist, Pieman will crash at the very beginning with a clear error message.
---
> Do not check if essentials.sh exists

- devices/rpi-2-b/ubuntu-bionic-armhf/pre-kernel-installation/10-patch-flash-kernel.sh
- devices/rpi-2-b/ubuntu-xenial-armhf/pre-kernel-installation/10-patch-flash-kernel.sh
- devices/rpi-3-b/ubuntu-bionic-arm64/pre-kernel-installation/10-patch-flash-kernel.sh
> Fix typo in 10-patch-flash-kernel.sh

- .travis.yml
- devices/rpi-2-b/ubuntu-bionic-armhf/pre-kernel-installation/10-patch-flash-kernel.sh
- devices/rpi-2-b/ubuntu-xenial-armhf/pre-kernel-installation/10-patch-flash-kernel.sh
- devices/rpi-3-b/ubuntu-bionic-arm64/pre-kernel-installation/10-patch-flash-kernel.sh
> Make hooks meet shellcheck requirements

- README.md
- pieman/test/runtest.py
> Change permissions from 664 to 775 on pieman/test/runtest.py

- .gitignore
- README.md
- helpers/base.sh
- pieman.sh
> Activate venv virtual environment if it exists

- essentials.sh
- helpers/base.sh
- pieman.sh
> Move check_dependencies bit higher

- essentials.sh
> Make check_pieman_version complain if there is any problem

- essentials.sh
> Make check_pieman_version complain if there is any problem 

- pieman.sh
- pieman/pieman/attrs.py
- pieman/test/runtest.py
> Fix shellcheck and pylint warning

- AUTHORS.md
> Move Denis Gavrilyuk to the maintainers from the contributors

- devices/README.md
- devices/__init__.py
- devices/opi-pc-plus/debian-buster-armhf/meta.yml
- devices/opi-pc-plus/kali-rolling-armhf/meta.yml
- devices/opi-pc-plus/meta.yml
- devices/opi-zero/debian-buster-armhf/meta.yml
- devices/opi-zero/kali-rolling-armhf/meta.yml
- devices/opi-zero/meta.yml
- devices/requirements.txt
- devices/rpi-2-b/alpine-3.12-armhf/meta.yml
- devices/rpi-2-b/meta.yml
- devices/rpi-2-b/ubuntu-bionic-armhf/meta.yml
- devices/rpi-2-b/ubuntu-xenial-armhf/meta.yml
- devices/rpi-3-b-plus/meta.yml
- devices/rpi-3-b-plus/ubuntu-focal-armhf/meta.yml
- devices/rpi-3-b/meta.yml
- devices/rpi-3-b/meta_raspbian-buster-armhf.yml
- devices/rpi-3-b/ubuntu-bionic-arm64/meta.yml
- devices/rpi-4-b/meta.yml
- devices/rpi-b/meta.yml
- devices/rpi-b/raspbian-buster-armhf/meta.yml
- devices/rpi-zero-w/meta.yml
- devices/rpi-zero/meta.yml
- devices/setup.py
> Make pieman_devices package out of devices directory

- docker/Dockerfile
> Prepend '/root/pieman/pieman/bin' to PATH

- README.md
> README: drop daily image builds section

- devices/opi-pc-plus/kali-rolling-armhf/meta.yml
- devices/opi-zero/kali-rolling-armhf/meta.yml
- devices/rpi-2-b/alpine-3.12-armhf/meta.yml
- devices/rpi-3-b/meta_raspbian-buster-armhf.yml
- devices/rpi-b/raspbian-buster-armhf/meta.yml
- devices/setup.py
> Update packages_url in devices
