tolstoyevsky/pieman

- functions.sh
check_if_variable_is_set used to check if a variable is equal to an empty string. If it was not, the variable was considered to be set. It's not correct behaviour of the function.
> Bugfix: check if variable is set

- pieman.sh
The reverted commit was supposed to change `docker-pieman.sh` instead of `pieman.sh`. By lack of attention, I approved the PR related to that. This commit corrects the mistake. 
Reverts tolstoyevsky/pieman#24
> Revert "Make docker-pieman.sh more portable"

- README.md
The Tweeter logo on the button has recently disappeared, but the fix returns it back.
> README: fix Tweeter button

- bootstrap/11-pm.sh
- devices/rpi-2-b/ubuntu-artful-armhf/pieman.yml
- devices/rpi-3-b/ubuntu-artful-arm64/pieman.yml
- functions.sh
- keys/devuan/raspberry-pi-archive-signing.key
- pieman.sh
- pieman/attrs.py
It makes it possible to build images without running Pieman with `ALLOW_UNAUTHENTICATED=true`.
> Add public keys to list of trusted keys

- pieman.sh
It allows preserving permissions. Otherwise, some of the executables will lose the setuid bit and, for example, calling `sudo` will end up with `/usr/bin/sudo must be owned by uid 0 and have the setuid bit set`.
Fixes #46.
> Call rsync with -p param

- functions.sh
`apt-key` might complain `/usr/bin/apt-key: cannot create /dev/null: Permission denied`. It causes problems with verifying signatures. Thus, mounting only /dev/pts is not enough in some cases.
> Mount the whole /dev to chroot environments

- docker/docker-entrypoint.sh
> docker: take into account that there can be extension

- bootstrap/10-rootfs-partition.sh
Otherwise, the setuid bit is lost.
> Call cp with --preserve param when BASE_DIR is set

- README.md
- bin/du.py
- functions.sh
- pieman.sh
`bin/du.py` calculates more accurately the size of the target chroot environment than `du`.
I collected all the logs from cusdeb.com related to `rsync` and the `No space left on device` error. The following `INCLUDES` resulted in the error:
* `INCLUDES=0install,389-admin,389-admin-console,aapt,ssh`
* `INCLUDES=uhd-host,swig,gnuradio-dev,gnuradio,gr-osmosdr,gr-radar,gr-rds,gr-air-modes,gr-radar-doc,gr-iio,nano,minicom,wifite`
* `INCLUDES=php,nano,apache2,tightvncserver,phpmyadmin,pptpd,vsftpd,php-cli`
* `INCLUDES=python3,python3-all,gnuradio,gnuradio-doc,gnuradio-dev`
* `INCLUDES=lxde`
* `INCLUDES=opencv-data,python-opencv`
* `INCLUDES=0install`
* `INCLUDES=php7.0,nginx,mysql-server`
I used the `INCLUDES` as test cases for the changes and everything is fine.
> Use `bin/du.py` instead of `du`

- bootstrap/11-pm.sh
It's quite confusing when I can see the message "exiting since CREATE_ONLY_CHROOT is set to true" when I build chroot environment. Let's use 'Success' message style to emphasize that chroot environment is built successfully.
> Use success message when chroot environment is done

- bootstrap/20-users.sh
Put a file with rules to /etc/sudoers.d instead. There are a couple of reasons to do that.
* It's not recommended to modify /etc/sudoers directly.
* The code, which is responsible for modification of /etc/sudoers, relies on on the content of the file which may vary from distro to distro.
> Do not modify /etc/sudoers

- bootstrap/12-pm.sh
- helpers/base.sh
* Involve such functions as `is_raspbian`, `is_ubuntu`, etc. to detect the operating system, using as little code as possible.
* Do not check if the current operating system is Debian, since Pieman doesn't support Debian so far. Check Devuan instead.
> Refactoring and enhancments

- helpers/pm.sh
Pieman crashed every time when `ENABLE_UNATTENDED_INSTALLATION` was set to `true`.
> Bugfix related to ENABLE_UNATTENDED_INSTALLATION

- .gitignore
- README.md
- docker/Dockerfile
- essentials.sh
- helpers/apk.sh
- helpers/base.sh
- helpers/deb.sh
- helpers/fs.sh
- helpers/image-attribs.sh
- pieman.sh
- test/test_functions.sh
- toolset.sh
* `debootstrap` is not required to be installed manually anymore.
* `apk.static` is not fetched every single time when images based on Alpine Linux are built.
* Before running Pieman checks the toolset. If it lacks some of the tools, it will install them itself.
> Combine apk and debootstrap in an entity called toolset

- devices/rpi-3-b/ubuntu-bionic-arm64/pieman.yml
> Keep only bcm2837-rpi-3-b.dtb in 64-bit images for RPi 3

- pieman.sh
`IMAGE_ROOTFS_SIZE` and `CREATE_ONLY_CHROOT` do not conflict with each other, so no need to call `check_mutually_exclusive_params`
> Fix chroot building

- bootstrap/12-pm.sh
- devices/rpi-b/raspbian-stretch-armhf/pieman.yml
Add `halt`, `reboot` and `shutdown` commands to Raspbian builds
> Add systemd-sysv to all Raspbian images

- docker-pieman.sh
The old variant of checking the version of Bash doesn't take Bash 5 into account.
> Fix checking Bash version in docker-pieman.sh

- README.md
- docker/rollout_fixes.sh
- helpers/base.sh
- helpers/toolset.sh
- pieman.sh
- test/test_functions.sh
- toolset.sh
Closes #160.
These changes help
* solving the problem related to building images on old systems such as Ubuntu 16.04 because of out-of-dated `qemu-arm-static`;
* reduce the number of dependencies which users have to install manually.
Now we can use the latest versions of `qemu-user-static` as a bonus.
---
> Move qemu-user-static to toolset

- toolset.sh
Nowadays python might mean Python 3, so it's necessary to explicitly specify that we need Python 2.
> Specify Python 2 explicitly in toolset.sh

- helpers/toolset.sh
We must update it since it's not possible to fetch `qemu-user-static` from Ubuntu 19.04 anymore.
```
wget http://mirrors.kernel.org/ubuntu/dists/disco/universe/binary-amd64/Packages.xz
```
ends up with 404.
---
> Make toolset fetch qemu-user-static from Ubuntu 20.04

- helpers/fs.sh
- pieman.sh
The idea of checking if the required directories exist doesn't seem good enough. It used to check 'bootstrap' and 'devices' which are the part of the source tree. Moreover, there is no interface to make Pieman use different ones.
---
> Remove check_required_directories function

- devices/setup.py
> Override sdist setuptools command in pieman-devices setup.py
